//Categories
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED'
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED'

export const SELECT_CATEGORY = 'SELECT_CATEGORY'


//Comments
export const FETCH_COMMENT = 'FETCH_COMMENT'
export const FETCH_COMMENT_FULFILLED = 'FETCH_COMMENT_FULFILLED'
export const FETCH_COMMENT_REJECTED = 'FETCH_COMMENT_REJECTED'

export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const FETCH_COMMENTS_FULFILLED = 'FETCH_COMMENTS_FULFILLED'
export const FETCH_COMMENTS_REJECTED = 'FETCH_COMMENTS_REJECTED'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const CREATE_COMMENT_REJECTED = 'CREATE_COMMENT_REJECTED'

export const EDIT_COMMENT = 'EDIT_COMMENT'
export const EDIT_COMMENT_REJECTED = 'EDIT_COMMENT_REJECTED'

export const DELETE_COMMENT = 'DELETE_COMMENT'

export const VOTE_ON_COMMENT = 'VOTE_ON_COMMENT'


//Posts
export const FETCH_POST = 'FETCH_POST'
export const FETCH_POST_FULFILLED = 'FETCH_POST_FULFILLED'
export const FETCH_POST_REJECTED = 'FETCH_POST_REJECTED'

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED'
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED'

export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY'
export const FETCH_POSTS_BY_CATEGORY_FULFILLED =
	'FETCH_POSTS_BY_CATEGORY_FULFILLED'
export const FETCH_POSTS_BY_CATEGORY_REJECTED =
	'FETCH_POSTS_BY_CATEGORY_REJECTED'

export const CREATE_POST = 'CREATE_POST'
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED'

export const EDIT_POST = 'EDIT_POST'
export const EDIT_POST_REJECTED = 'EDIT_POST_REJECTED'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_REJECTED = 'DELETE_POST_REJECTED'

export const SELECT_SORT_VALUE = 'SELECT_SORT_VALUE'

export const VOTE_ON_POST = 'VOTE_ON_POST'
